### ISSUE TITLE
Cannot run latest directory in a subfolder

### ISSUE THREAD

**Issue by fbartels** [bastienwirtz/homer#78]
Hi,

today I wanted to update my front facing Homer installation with the newest release from https://github.com/bastienwirtz/homer/releases/tag/120425999 and with this release it is no longer possible to run Homer in a subfolder.

From looking at index.html I could spot that all resources are now referenced from the root, like for example `/css/app.22d049fe.css`, while for running it from a subdir it should be like `css/app.22d049fe.css.

I tried looking into the Vue files, but could not yet make sense of the changes that need to be done.

**Comment by bastienwirtz** [comment]
Hi @fbartels 
Thanks for letting me know! It should be fine on the latest release (fixed in this commit : https://github.com/bastienwirtz/homer/commit/b0a0fdaa3b2fca33ee128f39d9bd1c9dcfda0db8#diff-0e893b3578ae3d5c8b98bac1c80756a7R10)

**Comment by fbartels** [comment]
Thanks, the site is now loading and showing properly again with the latest release.

Looking at the network tab one 404 error remains, but the only missing thing I can spot is the favicon:

`homer/assets/img/icons/android-chrome-192x192.png`
